springfox:
  title: '@title@'
  version: '@version@'

fint:
  consumer:
    cache:
      disabled:
        part: true
        korrespondansepart: true
        dokumentfil: true
        sak: true
spring:
  mvc:
    logResolvedException: false
